# Generated by Django 3.1.7 on 2024-05-24 11:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20240524_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapeddata',
            name='scraped_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
