# Generated by Django 3.1.7 on 2024-05-24 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20240524_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapeddata',
            name='scraped_at',
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='docx_file',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scrapeddata',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
