# Generated by Django 3.1.7 on 2024-05-24 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20240524_1954'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('docx_file', models.BinaryField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ScrapedText',
        ),
    ]
