# Generated by Django 3.1.7 on 2024-05-24 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20240524_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapeddata',
            name='docx_file',
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='table_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
